### ISSUE TITLE
SESSION/USERS

### ISSUE THREAD

**Issue by sramos9** [mayagold/routemapp#14]
- should be registered/logged in to edit anything
- can see a list of users
- can create routes/posts 
- can delete on their routes/posts

**Comment by lin1ood** [comment]
Register -- http://localhost:3000/sessions/register
-unique usernames enforced
-password rule applies (1 or more uppercase alpha & number with 8 character min)
-user/password stored in user model/schema/mongoose

Login - http://localhost:3000/session/login

Logout - http://localhost:3000/session/logout

Tested and verified.
